"use client";
import { useState } from "react";
import type { RescueRecord } from "@/features/dashboard/types";
import { createSupabaseBrowserClient } from "@/shared/lib/supabase/client";
export function ScheduleModal({ plan, classId, onClose, onSaved }: { plan: RescueRecord; classId: string; onClose: () => void; onSaved: () => void }) {
  const [scheduledFor, setScheduledFor] = useState(""); const [reminderAt, setReminderAt] = useState(""); const [note, setNote] = useState(""); const [notice, setNotice] = useState("");
  async function save() { const supabase = createSupabaseBrowserClient(); const { data: auth } = await supabase.auth.getUser(); if (!auth.user || !scheduledFor) { setNotice("Pilih masa intervensi dahulu."); return; } const { error } = await supabase.from("intervention_schedules").insert({ teacher_id: auth.user.id, class_id: classId, lesson_rescue_id: plan.id, scheduled_for: new Date(scheduledFor).toISOString(), reminder_at: reminderAt ? new Date(reminderAt).toISOString() : null, note: note.trim() || null }); if (error) { setNotice("Jadual tidak dapat disimpan."); return; } onSaved(); }
  return <div className="modal-backdrop"><section className="form-modal" role="dialog" aria-modal="true"><header className="workflow-header"><div><span className="eyebrow">JADUAL INTERVENSI</span><h2>{plan.title}</h2></div><button className="icon-button" onClick={onClose}>×</button></header><div className="workflow-body"><label className="form-field"><span>Masa intervensi</span><input type="datetime-local" value={scheduledFor} onChange={(event) => setScheduledFor(event.target.value)} /></label><label className="form-field"><span>Peringatan dalam aplikasi (pilihan)</span><input type="datetime-local" value={reminderAt} onChange={(event) => setReminderAt(event.target.value)} /></label><label className="form-field"><span>Nota (pilihan)</span><textarea value={note} onChange={(event) => setNote(event.target.value)} /></label><div className="modal-actions"><button className="secondary-button" onClick={onClose}>Batal</button><button className="primary-button" onClick={() => void save()}>Simpan jadual</button></div>{notice && <p className="workflow-notice">{notice}</p>}</div></section></div>;
}
